### ISSUE TITLE
fpgrowth error in R

### ISSUE THREAD

**Issue by krskalla** [jaroslav-kuchar/rCBA#3]
I am trying to fit a fpgrowth model on a in-built data set called Adult. While fitting a model, I was getting an error as shown below.

    Error in .jcall(jPruning, "[[Ljava/lang/String;", "fpgrowth", support,  : 
    method fpgrowth with signature (DDI)[[Ljava/lang/String; not found

I used the below R code to fit fpgrowth model.

    library(rCBA)
    data("Adult")
    Adult<-as(Adult,"transactions")
    rules = rCBA::fpgrowth(Adult, support=0.001, confidence=0.5, maxLength=2)

What's wrong with the above code?

**Comment by JMason88** [comment]
I have the same issue. Below my code:

```{r}
library(rCBA)
library(rJava)
data("iris")
train <- sapply(iris, as.factor)
train <- data.frame(train, check.names = FALSE)
transactions <- as(train, "transactions")
reglas <- fpgrowth(transactions, support = 0.01, confidence = 0.7, maxLength = 3, consequent = NULL, verbose = TRUE, parallel = FALSE)
summary(transactions)
```

**Comment by jaroslav-kuchar** [comment]
The `fpgrowth` implementation is limited to specific format of rules now. You have to choose the consequent. The selected name will be thus the only member of the RHS of the rule and the remaining items will be on the LHS.
e.g. 
```
# Adult
rules = rCBA::fpgrowth(Adult, support=0.001, confidence=0.5, maxLength=2, consequent="income")
# iris
reglas <- fpgrowth(transactions, support = 0.01, confidence = 0.7, maxLength = 3, consequent = "Species", verbose = TRUE, parallel = FALSE)
```

**Comment by janpristovnik** [comment]
What would be the right consequent for Groceries data from arules package? 

Link:
https://www.rdocumentation.org/packages/arules/versions/1.6-4/topics/Groceries
